-- /*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
-- /*!40103 SET TIME_ZONE='+00:00' */;
-- /*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
-- /*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
-- /*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
-- /*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;
-- DROP TABLE IF EXISTS `areas`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `areas` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `city_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `areas_city_id_foreign` (`city_id`),
--   CONSTRAINT `areas_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `attributes`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `attributes` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `values` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL CHECK (json_valid(`values`)),
--   `product_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `attributes_product_id_foreign` (`product_id`),
--   CONSTRAINT `attributes_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `brands`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `brands` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `brands_company_id_foreign` (`company_id`),
--   CONSTRAINT `brands_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `categories`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `categories` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `parent_id` bigint(20) unsigned DEFAULT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `categories_parent_id_foreign` (`parent_id`),
--   KEY `categories_company_id_foreign` (`company_id`),
--   CONSTRAINT `categories_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
--   CONSTRAINT `categories_parent_id_foreign` FOREIGN KEY (`parent_id`) REFERENCES `categories` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `cities`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `cities` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `country_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `cities_country_id_foreign` (`country_id`),
--   CONSTRAINT `cities_country_id_foreign` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `client_groups`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `client_groups` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `discount` double(8,2) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `client_groups_name_company_id_unique` (`name`,`company_id`),
--   KEY `client_groups_company_id_foreign` (`company_id`),
--   CONSTRAINT `client_groups_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `clients`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `clients` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `phone_1` varchar(255) NOT NULL,
--   `phone_2` varchar(255) DEFAULT NULL,
--   `address` varchar(255) NOT NULL,
--   `area_id` bigint(20) unsigned NOT NULL,
--   `city_id` bigint(20) unsigned NOT NULL,
--   `country_id` bigint(20) unsigned NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `client_group_id` bigint(20) unsigned DEFAULT NULL,
--   `links` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`links`)),
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `clients_company_id_foreign` (`company_id`),
--   KEY `clients_client_group_id_foreign` (`client_group_id`),
--   KEY `clients_area_id_foreign` (`area_id`),
--   KEY `clients_city_id_foreign` (`city_id`),
--   KEY `clients_country_id_foreign` (`country_id`),
--   CONSTRAINT `clients_area_id_foreign` FOREIGN KEY (`area_id`) REFERENCES `areas` (`id`),
--   CONSTRAINT `clients_city_id_foreign` FOREIGN KEY (`city_id`) REFERENCES `cities` (`id`),
--   CONSTRAINT `clients_client_group_id_foreign` FOREIGN KEY (`client_group_id`) REFERENCES `client_groups` (`id`),
--   CONSTRAINT `clients_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
--   CONSTRAINT `clients_country_id_foreign` FOREIGN KEY (`country_id`) REFERENCES `countries` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `companies`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `companies` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `company_type` varchar(255) NOT NULL,
--   `max_users` int(11) NOT NULL,
--   `max_orders` int(11) NOT NULL,
--   `active` tinyint(1) NOT NULL DEFAULT 1,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   `code` varchar(255) NOT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `countries`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `countries` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `failed_jobs`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `failed_jobs` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `uuid` varchar(255) NOT NULL,
--   `connection` text NOT NULL,
--   `queue` text NOT NULL,
--   `payload` longtext NOT NULL,
--   `exception` longtext NOT NULL,
--   `failed_at` timestamp NOT NULL DEFAULT current_timestamp(),
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `failed_jobs_uuid_unique` (`uuid`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `media`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `media` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `file_name` varchar(255) NOT NULL,
--   `mime_type` varchar(255) NOT NULL,
--   `path` varchar(255) NOT NULL,
--   `disk` varchar(255) NOT NULL DEFAULT 'local',
--   `file_hash` varchar(64) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `collection` varchar(255) DEFAULT NULL,
--   `collection_id` int(11) DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `media_company_id_foreign` (`company_id`),
--   CONSTRAINT `media_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `migrations`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `migrations` (
--   `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
--   `migration` varchar(255) NOT NULL,
--   `batch` int(11) NOT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `order_status`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `order_status` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `order_id` bigint(20) unsigned NOT NULL,
--   `status_id` bigint(20) unsigned NOT NULL,
--   `admin_id` bigint(20) unsigned NOT NULL,
--   `note` varchar(255) NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   `current` tinyint(1) NOT NULL,
--   PRIMARY KEY (`id`),
--   KEY `order_status_order_id_foreign` (`order_id`),
--   KEY `order_status_status_id_foreign` (`status_id`),
--   KEY `order_status_admin_id_foreign` (`admin_id`),
--   CONSTRAINT `order_status_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`),
--   CONSTRAINT `order_status_order_id_foreign` FOREIGN KEY (`order_id`) REFERENCES `orders` (`id`),
--   CONSTRAINT `order_status_status_id_foreign` FOREIGN KEY (`status_id`) REFERENCES `statuses` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `orders`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `orders` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `phone_1` varchar(255) NOT NULL,
--   `phone_2` varchar(255) DEFAULT NULL,
--   `address` varchar(255) NOT NULL,
--   `country_id` varchar(255) NOT NULL,
--   `city_id` varchar(255) NOT NULL,
--   `area_id` varchar(255) NOT NULL,
--   `total` double(8,2) NOT NULL,
--   `client_id` bigint(20) unsigned NOT NULL,
--   `status_id` bigint(20) unsigned NOT NULL,
--   `admin_id` bigint(20) unsigned NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   `order_code` varchar(255) NOT NULL,
--   PRIMARY KEY (`id`),
--   KEY `orders_company_id_foreign` (`company_id`),
--   KEY `orders_admin_id_foreign` (`admin_id`),
--   KEY `orders_client_id_foreign` (`client_id`),
--   CONSTRAINT `orders_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`),
--   CONSTRAINT `orders_client_id_foreign` FOREIGN KEY (`client_id`) REFERENCES `clients` (`id`),
--   CONSTRAINT `orders_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `orders_items`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `orders_items` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `orders_id` bigint(20) unsigned NOT NULL,
--   `variants_id` bigint(20) unsigned NOT NULL,
--   `quantity` int(10) unsigned NOT NULL,
--   `warehouse_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `orders_items_orders_id_foreign` (`orders_id`),
--   KEY `orders_items_variants_id_foreign` (`variants_id`),
--   KEY `orders_items_warehouse_id_foreign` (`warehouse_id`),
--   CONSTRAINT `orders_items_orders_id_foreign` FOREIGN KEY (`orders_id`) REFERENCES `orders` (`id`),
--   CONSTRAINT `orders_items_variants_id_foreign` FOREIGN KEY (`variants_id`) REFERENCES `variants` (`id`),
--   CONSTRAINT `orders_items_warehouse_id_foreign` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `password_reset_tokens`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `password_reset_tokens` (
--   `email` varchar(255) NOT NULL,
--   `token` varchar(255) NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`email`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `permissions`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `permissions` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `slug` varchar(255) NOT NULL,
--   `resource_name` varchar(255) NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `personal_access_tokens`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `personal_access_tokens` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `tokenable_type` varchar(255) NOT NULL,
--   `tokenable_id` bigint(20) unsigned NOT NULL,
--   `name` varchar(255) NOT NULL,
--   `token` varchar(64) NOT NULL,
--   `abilities` text DEFAULT NULL,
--   `last_used_at` timestamp NULL DEFAULT NULL,
--   `expires_at` timestamp NULL DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `personal_access_tokens_token_unique` (`token`),
--   KEY `personal_access_tokens_tokenable_type_tokenable_id_index` (`tokenable_type`,`tokenable_id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `products`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `products` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `description` longtext DEFAULT NULL,
--   `cost` double(8,2) NOT NULL,
--   `price` double(8,2) NOT NULL,
--   `before_sale_price` double(8,2) DEFAULT NULL,
--   `supplier_id` bigint(20) unsigned NOT NULL,
--   `brand_id` bigint(20) unsigned NOT NULL,
--   `category_id` bigint(20) unsigned NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `products_supplier_id_foreign` (`supplier_id`),
--   KEY `products_brand_id_foreign` (`brand_id`),
--   KEY `products_category_id_foreign` (`category_id`),
--   KEY `products_company_id_foreign` (`company_id`),
--   CONSTRAINT `products_brand_id_foreign` FOREIGN KEY (`brand_id`) REFERENCES `brands` (`id`),
--   CONSTRAINT `products_category_id_foreign` FOREIGN KEY (`category_id`) REFERENCES `categories` (`id`),
--   CONSTRAINT `products_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
--   CONSTRAINT `products_supplier_id_foreign` FOREIGN KEY (`supplier_id`) REFERENCES `suppliers` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `roles`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `roles` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `roles_company_id_foreign` (`company_id`),
--   CONSTRAINT `roles_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `roles_permissions`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `roles_permissions` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `roles_id` bigint(20) unsigned NOT NULL,
--   `permissions_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `roles_permissions_roles_id_foreign` (`roles_id`),
--   KEY `roles_permissions_permissions_id_foreign` (`permissions_id`),
--   CONSTRAINT `roles_permissions_permissions_id_foreign` FOREIGN KEY (`permissions_id`) REFERENCES `permissions` (`id`) ON DELETE CASCADE,
--   CONSTRAINT `roles_permissions_roles_id_foreign` FOREIGN KEY (`roles_id`) REFERENCES `roles` (`id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `sessions`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `sessions` (
--   `id` varchar(255) NOT NULL,
--   `user_id` bigint(20) unsigned DEFAULT NULL,
--   `ip_address` varchar(45) DEFAULT NULL,
--   `user_agent` text DEFAULT NULL,
--   `payload` longtext NOT NULL,
--   `last_activity` int(11) NOT NULL,
--   PRIMARY KEY (`id`),
--   KEY `sessions_user_id_index` (`user_id`),
--   KEY `sessions_last_activity_index` (`last_activity`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `shipping_companies`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `shipping_companies` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `username` varchar(255) NOT NULL,
--   `password` varchar(255) NOT NULL,
--   `url` varchar(255) NOT NULL,
--   `mega_company_id` varchar(255) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `shipping_companies_company_id_foreign` (`company_id`),
--   CONSTRAINT `shipping_companies_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `statuses`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `statuses` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   `default` tinyint(1) NOT NULL DEFAULT 0,
--   PRIMARY KEY (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `stocks`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `stocks` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `admin_id` bigint(20) unsigned NOT NULL,
--   `warehouse_id` bigint(20) unsigned NOT NULL,
--   `variant_id` bigint(20) unsigned NOT NULL,
--   `order_id` bigint(20) unsigned DEFAULT NULL,
--   `quantity` int(11) NOT NULL,
--   `note` varchar(255) DEFAULT NULL,
--   `type` enum('move','buy','sell','returned_orders','returned_suppliers') NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `stocks_variant_id_foreign` (`variant_id`),
--   KEY `stocks_company_id_foreign` (`company_id`),
--   KEY `stocks_admin_id_foreign` (`admin_id`),
--   KEY `stocks_warehouse_id_foreign` (`warehouse_id`),
--   CONSTRAINT `stocks_admin_id_foreign` FOREIGN KEY (`admin_id`) REFERENCES `users` (`id`),
--   CONSTRAINT `stocks_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
--   CONSTRAINT `stocks_variant_id_foreign` FOREIGN KEY (`variant_id`) REFERENCES `variants` (`id`),
--   CONSTRAINT `stocks_warehouse_id_foreign` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `suppliers`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `suppliers` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `address` varchar(255) NOT NULL,
--   `phone` varchar(255) NOT NULL,
--   `payment_methods` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`payment_methods`)),
--   `contacts` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin DEFAULT NULL CHECK (json_valid(`contacts`)),
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `suppliers_name_company_id_unique` (`name`,`company_id`),
--   KEY `suppliers_company_id_foreign` (`company_id`),
--   CONSTRAINT `suppliers_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `users`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `users` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `email` varchar(255) NOT NULL,
--   `phone_1` varchar(255) NOT NULL,
--   `password` varchar(255) NOT NULL,
--   `active` tinyint(1) NOT NULL DEFAULT 1,
--   `is_admin` tinyint(1) NOT NULL DEFAULT 0,
--   `company_id` bigint(20) unsigned DEFAULT NULL,
--   `warehouse_id` bigint(20) unsigned DEFAULT NULL,
--   `role_id` bigint(20) unsigned NOT NULL,
--   `remember_token` varchar(100) DEFAULT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `users_email_unique` (`email`),
--   UNIQUE KEY `users_phone_1_unique` (`phone_1`),
--   KEY `users_role_id_foreign` (`role_id`),
--   KEY `users_company_id_foreign` (`company_id`),
--   KEY `users_warehouse_id_foreign` (`warehouse_id`),
--   CONSTRAINT `users_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`),
--   CONSTRAINT `users_role_id_foreign` FOREIGN KEY (`role_id`) REFERENCES `roles` (`id`),
--   CONSTRAINT `users_warehouse_id_foreign` FOREIGN KEY (`warehouse_id`) REFERENCES `warehouses` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `variants`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `variants` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `quantity` int(11) NOT NULL DEFAULT 0,
--   `price` double(8,2) NOT NULL,
--   `sku` varchar(255) DEFAULT NULL,
--   `is_default` tinyint(1) NOT NULL DEFAULT 0,
--   `product_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   KEY `variants_product_id_foreign` (`product_id`),
--   CONSTRAINT `variants_product_id_foreign` FOREIGN KEY (`product_id`) REFERENCES `products` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `variants_attributes`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `variants_attributes` (
--   `value` varchar(255) NOT NULL,
--   `variant_id` bigint(20) unsigned NOT NULL,
--   `attribute_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`variant_id`,`attribute_id`),
--   KEY `variants_attributes_attribute_id_foreign` (`attribute_id`),
--   CONSTRAINT `variants_attributes_attribute_id_foreign` FOREIGN KEY (`attribute_id`) REFERENCES `attributes` (`id`) ON DELETE CASCADE,
--   CONSTRAINT `variants_attributes_variant_id_foreign` FOREIGN KEY (`variant_id`) REFERENCES `variants` (`id`) ON DELETE CASCADE
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- DROP TABLE IF EXISTS `warehouses`;
-- /*!40101 SET @saved_cs_client     = @@character_set_client */;
-- /*!40101 SET character_set_client = utf8 */;
-- CREATE TABLE `warehouses` (
--   `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
--   `name` varchar(255) NOT NULL,
--   `company_id` bigint(20) unsigned NOT NULL,
--   `created_at` timestamp NULL DEFAULT NULL,
--   `updated_at` timestamp NULL DEFAULT NULL,
--   PRIMARY KEY (`id`),
--   UNIQUE KEY `warehouses_name_company_id_unique` (`name`,`company_id`),
--   KEY `warehouses_company_id_foreign` (`company_id`),
--   CONSTRAINT `warehouses_company_id_foreign` FOREIGN KEY (`company_id`) REFERENCES `companies` (`id`)
-- ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
-- /*!40101 SET character_set_client = @saved_cs_client */;
-- /*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

-- /*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
-- /*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
-- /*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
-- /*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- INSERT INTO `migrations` VALUES (1,'2014_10_12_100000_create_password_reset_tokens_table',1);
-- INSERT INTO `migrations` VALUES (2,'2019_08_19_000000_create_failed_jobs_table',1);
-- INSERT INTO `migrations` VALUES (3,'2019_12_14_000001_create_personal_access_tokens_table',1);
-- INSERT INTO `migrations` VALUES (4,'2023_07_12_132946_create_companies_table',1);
-- INSERT INTO `migrations` VALUES (5,'2023_07_13_080917_create_roles_table',1);
-- INSERT INTO `migrations` VALUES (6,'2023_07_13_082620_create_permissions_table',1);
-- INSERT INTO `migrations` VALUES (7,'2023_07_16_082931_create_roles_permissions_table',1);
-- INSERT INTO `migrations` VALUES (8,'2023_07_17_104143_create_media_table',1);
-- INSERT INTO `migrations` VALUES (9,'2023_07_18_084447_create_countries_table',1);
-- INSERT INTO `migrations` VALUES (10,'2023_07_18_084501_create_cities_table',1);
-- INSERT INTO `migrations` VALUES (11,'2023_07_18_084510_create_areas_table',1);
-- INSERT INTO `migrations` VALUES (12,'2023_07_18_092642_create_brands_table',1);
-- INSERT INTO `migrations` VALUES (13,'2023_07_18_114836_create_categories_table',1);
-- INSERT INTO `migrations` VALUES (14,'2023_07_19_065257_create_client_groups_table',1);
-- INSERT INTO `migrations` VALUES (15,'2023_07_19_073004_create_clients_table',1);
-- INSERT INTO `migrations` VALUES (16,'2023_07_19_141136_create_suppliers_table',1);
-- INSERT INTO `migrations` VALUES (17,'2023_07_20_104632_create_warehouses_table',1);
-- INSERT INTO `migrations` VALUES (18,'2023_07_21_000000_create_users_table',1);
-- INSERT INTO `migrations` VALUES (30,'2023_07_24_093728_create_products_table',2);
-- INSERT INTO `migrations` VALUES (31,'2023_07_24_094317_create_attributes_table',2);
-- INSERT INTO `migrations` VALUES (32,'2023_07_24_094509_create_variants_table',2);
-- INSERT INTO `migrations` VALUES (33,'2023_07_24_094751_create_variants_attributes_table',2);
-- INSERT INTO `migrations` VALUES (34,'2023_08_02_151227_create_stocks_table',2);
-- INSERT INTO `migrations` VALUES (35,'2023_08_06_094038_create_statuses_table',2);
-- INSERT INTO `migrations` VALUES (36,'2023_08_06_095231_create_order_table',3);
-- INSERT INTO `migrations` VALUES (37,'2023_08_07_144549_create_orders_items_table',3);
-- INSERT INTO `migrations` VALUES (38,'2023_08_08_104409_add_default_to_statuses_table',3);
-- INSERT INTO `migrations` VALUES (39,'2023_08_09_110428_add_code_to_company_table',4);
-- INSERT INTO `migrations` VALUES (40,'2023_08_09_110919_add_order_code_to_orders_table',4);
-- INSERT INTO `migrations` VALUES (41,'2023_08_09_124853_create_order_status_table',4);
-- INSERT INTO `migrations` VALUES (43,'2023_08_09_152917_add_current_to_order_status_table',5);
-- INSERT INTO `migrations` VALUES (44,'2023_08_10_181202_create_sessions_table',6);
-- INSERT INTO `migrations` VALUES (45,'2023_08_13_164228_change_products_table',7);
-- INSERT INTO `migrations` VALUES (47,'2023_08_16_140517_create_shipping_companies_table',8);
-- INSERT INTO `migrations` VALUES (49,'2023_08_17_123053_drop_company_id_on_statuses',9);
